platform :ios, '9.2'
use_modular_headers!
use_frameworks!
def common
    pod 'PrivatePushnotificationPlugin', :path => '../'
end

pod 'AWSCore' ,:modular_headers => true
pod  'AWSPinpoint',:modular_headers => true
pod  'AWSMobileClient',:modular_headers => true

target 'PrivatePushnotificationPlugin_Example' do
    common
  pod 'AWSCore',:modular_headers => true
  pod  'AWSPinpoint',:modular_headers => true
  pod  'AWSMobileClient',:modular_headers => true

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            if target.name != "PrivatePushnotificationPlugin" || target.name != "PrivatePushnotificationPlugin_Example" then
                config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
            end
        end
    end
end
