
platform :ios, '9.0'
use_frameworks!
pod  'AWSPinpoint', '~> 2.7.0'
pod  'AWSMobileClient', '~> 2.7.0'

target 'PrivatePushnotificationPlugin_Example' do
    use_frameworks!
  pod 'PrivatePushnotificationPlugin', :path => '../'
  pod  'AWSPinpoint', '~> 2.7.0'
  pod  'AWSMobileClient', '~> 2.7.0'

  target 'PrivatePushnotificationPlugin_Tests' do
    inherit! :search_paths
    use_frameworks!

    pod  'AWSPinpoint', '~> 2.7.0'
    pod  'AWSMobileClient', '~> 2.7.0'
    
  end
end
